const scenes = [
    {id: 250005, title: "Soft Body 2", categories: [], unmissable: false, series:"Soft Bodies", desc: "Encore une fois..."},
    {id: 250002, title: "Something Interesting 2", categories: [], unmissable: false, series:"Something Interesting", desc: "Quand les limites d'Algodoo donnent des résultats intéressants."},
    {id: 250001, title: "Garage Door Opening 1", categories: [], unmissable: false, series:"Garage Door Openings", desc: "Juste une porte de garage.<br>Ouais, je sais, c'est très intéressant."},
    {id: 249918, title: "Soft Body 1", categories: [], unmissable: false, series:"Soft Bodies", desc: "Je pense que j'ai atteint le summun de l'ennui."},
    {id: 249831, title: "Marble Race 1", categories: ["Marble Race"], unmissable: true, series:"Marble Races", desc: "Quand on parle de course de billes..."},
    {id: 249811, title: "Chain Link vs Spring", categories: [], unmissable: false, series:"", desc: "Petite expérience avec un maillon de chaîne et un ressort."},
    {id: 249687, title: "Introducing the Value-Changing Balls", categories: [], unmissable: false, series:"", desc: "Parfaites pour les courses de billes."},
    {id: 249656, title: "Something Unuseful 9", categories: [], unmissable: false, series:"Something Unuseful", desc: "J'aime bien les arcs-en-ciel.<br>Pas vous ?"},
    {id: 249638, title: "Rainbow Ball V2", categories: [], unmissable: false, series:"", desc: "En voilà une de vraie bille arc-en-ciel !"},
    {id: 249509, title: "Accurate Stopwatch", categories: [], unmissable: false, series:"", desc: "Juste un chronomètre.<br>Rien de plus à voir ici..."},
    {id: 249481, title: "What Happens If You Go WAY TOO FAST In Algodoo ?", categories: [], unmissable: false, series:"", desc: "Pas sûr que la vraie physique fonctionne comme ça..."},
    {id: 249456, title: "Something Unuseful 8", categories: [], unmissable: false, series:"Something Unuseful", desc: "J'ai encore manqué d'originalité."},
    {id: 249434, title: "Something Unuseful 7", categories: [], unmissable: false, series:"Something Unuseful", desc: "Même base.<br>Forme différente."},
    {id: 249433, title: "Something Unuseful 6", categories: [], unmissable: false, series:"Something Unuseful", desc: "Je me suis inspiré d'un niveau sur Geometry Dash.<br>Je sais plus lequel..."},
    {id: 249416, title: "Destroying the Physics with a Single Block", categories: [], unmissable: false, series:"", desc: "Lorsque les objets ne respectent plus les lois de la physique..."},
    {id: 249389, title: "Something Unuseful 5", categories: [], unmissable: false, series:"Something Unuseful", desc: "Et la petite maison fait BOOM !"},
    {id: 249385, title: "Why ? 1", categories: [], unmissable: false, series:"", desc: "Dans le même style que <i>Something Interesting</i>, j'explore cette fois-ci les limites d'Algodoo qui n'ont aucun sens."},
    {id: 249382, title: "(Better) Volcano Eruption", categories: [], unmissable: false, series:"", desc: "J'ai retravaillé le visuel cette fois-ci."},
    {id: 249283, title: "Contraption 1", categories: [], unmissable: false, series:"Contraptions", desc: "Comme les circuits de billes de notre enfance."},
    {id: 249265, title: "Something Unuseful 4", categories: [], unmissable: false, series:"Something Unuseful", desc: "Encore une de ces scènes inutiles..."},
    {id: 248379, title: "Imperfect Thing 1", categories: [], unmissable: false, series:"Imperfect Things", desc: "C'est la seule scène dont le développement n'est pas terminé<br>J'avais plus d'idées pour corriger la machine donc j'ai fini par demander de l'aide à la communauté."},
    {id: 248287, title: "Color Mixer", categories: [], unmissable: false, series:"Color Mixers", desc: "Un simple mélangeur de couleurs.<br>Rien de plus simple."},
    {id: 248183, title: "Something Interesting 1", categories: [], unmissable: false, series:"Something Interesting", desc: "C'est en expérimentant des choses sur Algodoo que je suis tombé sur ce comportement intéressant.<br>Ça m'a donné envie de tester d'autres comportements intéressants."},
    {id: 248071, title: "Lava Flow", categories: [], unmissable: false, series:"", desc: "Je manque encore d'originalité..."},
    {id: 247996, title: "Fountain", categories: [], unmissable: false, series:"", desc: "J'ai réutilisé le code de <i>Volcano Eruption</i> pour faire cette scène.<br>Rien de très intéressant..."},
    {id: 247994, title: "Volcano Eruption", categories: [], unmissable: false, series:"", desc: "C'est ma première scène avec du script à l'intérieur.<br>Elle était plutôt simple pour être honnête."},
    {id: 247828, title: "Something Unuseful 3", categories: [], unmissable: false, series:"Something Unuseful", desc: "Je crois que je manque d'originalité..."},
    {id: 247594, title: "Something Unuseful 2", categories: [], unmissable: false, series:"Something Unuseful", desc: "J'ai réutilisé ma boule arc-en-ciel pour faire cette scène.<br>C'est joli mais ça sert toujours à rien."},
    {id: 247593, title: "Rainbow Ball", categories: [], unmissable: false, series:"", desc: "J'avoue que la scène porte mal son nom parce que seule la trainée de la boule est arc-en-ciel.<br>Peut-être faudra t-il en faire une autre..."},
    {id: 247436, title: "The Impossible Triangle", categories: [], unmissable: false, series:"", desc: "Juste un triangle impossible.<br>Rien de très utile."},
    {id: 246780, title: "Something Unuseful 1", categories: [], unmissable: false, series:"Something Unuseful", desc: "C'est en lui donnant son nom que la suite est venue.<br><i>\"C'est joli mais ça ne sert à rien...\"</i> Cette phrase accompagne toutes les autres scènes de la série Something Unuseful, et cette scène est la première.<br>Amusez-vous bien !"},
    {id: 246777, title: "Chaotic Pendulum", categories: [], unmissable: false, series:"", desc: "Un pendule chaotique.<br>Que dire de plus ?"},
    {id: 246719, title: "Automatic Bowling Machine", categories: ["Bowling", "Game"], unmissable: true, series:"Automatic Bowling Machines", desc: "La première scène réalisée, donc elle a un caractère plutôt historique.<br>C'est un système automatisé de bowling (comme on peut en trouver plein sur Algodoo), et j'en étais plutôt fier à l'époque.<br>Mais avec le recul, j'ai trouvé plusieurs problèmes et ça m'a donné envie d'en faire d'autres (consultez la série)."},
]